---

name: Testing Farm in TypeScript PoC

description: Please do not use this action in production

inputs:
  pr:
    required: true
    description: Pull request number
  token:
    required: true
    default: ${{ github.token }}
    description: GitHub token

runs:
  using: 'node16'
  main: 'dist/index.js'

...
